update pr workflows

diff --git a/.github/workflows/close-pr.yml b/.github/workflows/close-pr.yml
--- a/.github/workflows/close-pr.yml
+++ b/.github/workflows/close-pr.yml
@@ -5,7 +5,6 @@ on:
       - closed
 
 permissions:
-  id-token: write
   contents: read
 
 jobs:
@@ -19,29 +18,32 @@ jobs:
           targetAppName="darts-stg"
           appId="dec3be30-6325-4335-b898-eb01985d6c90"
 
-          az login --service-principal --username ${{ secrets.SP_CLIENT_ID}} -p=${{ secrets.SP_SECRET_KEY}} --tenant ${{ secrets.SP_TENANT_ID}} --allow-no-subscriptions
-          
+          if [[ -z "${AZURE_CLIENT_ID}" || -z "${AZURE_CLIENT_SECRET}" || -z "${AZURE_TENANT_ID}" ]]; then
+            echo "::error::Missing Azure service principal secrets for internal AD callback URL cleanup"
+            exit 1
+          fi
+
+          az login --service-principal --username "${AZURE_CLIENT_ID}" --password="${AZURE_CLIENT_SECRET}" --tenant "${AZURE_TENANT_ID}" --allow-no-subscriptions
+
           replyUrls=$(az ad app show --id "$appId" --query "web.redirectUris" -o json --only-show-errors)
           echo "Found callback URLs"
           echo $replyUrls
 
-          readarray -t my_array < <(echo "$replyUrls" | jq -c '.[]')
-          for item in "${my_array[@]}"; do
-            if [[ $item != "\"$authCallbackUrl\"" && $item != "\"$logoutUrl\"" ]]; then
-              replyUrlString+="$item,"
-            fi
-          done
+          replyUrls=$(jq --arg authCallbackUrl "$authCallbackUrl" --arg logoutUrl "$logoutUrl" -c 'map(select(. != $authCallbackUrl and . != $logoutUrl))' <<< "$replyUrls")
 
-          echo "Setting callback URLs: $replyUrlString"
+          echo "Setting callback URLs: $replyUrls"
 
           objectId=$(az ad app list --all --filter "displayname eq '${targetAppName}'" --query "[0].id" -o tsv --only-show-errors)
           objectId=${objectId//[$'\t\r\n']/}
           echo "Object ID: $objectId"
           restUrl="https://graph.microsoft.com/v1.0/applications/${objectId//[$'\t\r\n']/}"
           echo "Calling: $restUrl"
-          az rest --method PATCH --header "Content-Type=application/json" --uri $restUrl --body "{\"web\":{\"redirectUris\":[$replyUrlString]}}" #--debug
+          az rest --method PATCH --header "Content-Type=application/json" --uri $restUrl --body "{\"web\":{\"redirectUris\":$replyUrls}}" #--debug
         env:
           PR_NUMBER: ${{ github.event.number }}
+          AZURE_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
+          AZURE_CLIENT_SECRET: ${{ secrets.SP_SECRET_KEY }}
+          AZURE_TENANT_ID: ${{ secrets.SP_TENANT_ID }}
   remove-external-ad-b2c-callback-urls:
     runs-on: ubuntu-latest
     steps:
@@ -52,26 +54,29 @@ jobs:
           targetAppName="darts"
           appId="363c11cb-48b9-44bf-9d06-9a3973f6f413"
 
-          az login --service-principal --username ${{ secrets.SP_CLIENT_ID_B2C}} -p=${{ secrets.SP_SECRET_KEY_B2C}} --tenant ${{ secrets.SP_TENANT_ID_B2C}} --allow-no-subscriptions
-          
+          if [[ -z "${AZURE_CLIENT_ID}" || -z "${AZURE_CLIENT_SECRET}" || -z "${AZURE_TENANT_ID}" ]]; then
+            echo "::error::Missing Azure service principal secrets for external AD B2C callback URL cleanup"
+            exit 1
+          fi
+
+          az login --service-principal --username "${AZURE_CLIENT_ID}" --password="${AZURE_CLIENT_SECRET}" --tenant "${AZURE_TENANT_ID}" --allow-no-subscriptions
+
           replyUrls=$(az ad app show --id "$appId" --query "web.redirectUris" -o json --only-show-errors)
           echo "Found callback URLs"
           echo $replyUrls
 
-          readarray -t my_array < <(echo "$replyUrls" | jq -c '.[]')
-          for item in "${my_array[@]}"; do
-            if [[ $item != "\"$authCallbackUrl\"" && $item != "\"$logoutUrl\"" ]]; then
-              replyUrlString+="$item,"
-            fi
-          done
+          replyUrls=$(jq --arg authCallbackUrl "$authCallbackUrl" --arg logoutUrl "$logoutUrl" -c 'map(select(. != $authCallbackUrl and . != $logoutUrl))' <<< "$replyUrls")
 
-          echo "Setting callback URLs: $replyUrlString"
+          echo "Setting callback URLs: $replyUrls"
 
           objectId=$(az ad app list --all --filter "displayname eq '${targetAppName}'" --query "[0].id" -o tsv --only-show-errors)
           objectId=${objectId//[$'\t\r\n']/}
           echo "Object ID: $objectId"
           restUrl="https://graph.microsoft.com/v1.0/applications/${objectId//[$'\t\r\n']/}"
           echo "Calling: $restUrl"
-          az rest --method PATCH --header "Content-Type=application/json" --uri $restUrl --body "{\"web\":{\"redirectUris\":[$replyUrlString]}}" #--debug
+          az rest --method PATCH --header "Content-Type=application/json" --uri $restUrl --body "{\"web\":{\"redirectUris\":$replyUrls}}" #--debug
         env:
           PR_NUMBER: ${{ github.event.number }}
+          AZURE_CLIENT_ID: ${{ secrets.SP_CLIENT_ID_B2C }}
+          AZURE_CLIENT_SECRET: ${{ secrets.SP_SECRET_KEY_B2C }}
+          AZURE_TENANT_ID: ${{ secrets.SP_TENANT_ID_B2C }}
