update pr workflows

diff --git a/.github/workflows/on-pr.yml b/.github/workflows/on-pr.yml
--- a/.github/workflows/on-pr.yml
+++ b/.github/workflows/on-pr.yml
@@ -1,13 +1,12 @@
 ---
 name: PR Tasks
 on:
-  pull_request:
+  pull_request_target:
     types:
       - opened
       - reopened
       - synchronize
 permissions:
-  id-token: write
   contents: read
 jobs:
   set-internal-ad-callback-urls:
@@ -20,34 +19,37 @@ jobs:
           targetAppName="darts-stg"
           appId="dec3be30-6325-4335-b898-eb01985d6c90"
 
-          az login --service-principal --username ${{ secrets.SP_CLIENT_ID}} -p=${{ secrets.SP_SECRET_KEY}} --tenant ${{ secrets.SP_TENANT_ID}} --allow-no-subscriptions
-          
+          if [[ -z "${AZURE_CLIENT_ID}" || -z "${AZURE_CLIENT_SECRET}" || -z "${AZURE_TENANT_ID}" ]]; then
+            echo "::error::Missing Azure service principal secrets for internal AD callback URL setup"
+            exit 1
+          fi
+
+          az login --service-principal --username "${AZURE_CLIENT_ID}" --password="${AZURE_CLIENT_SECRET}" --tenant "${AZURE_TENANT_ID}" --allow-no-subscriptions
+
           replyUrls=$(az ad app show --id "$appId" --query "web.redirectUris" -o json --only-show-errors)
           echo "Found callback URLs"
           echo $replyUrls
 
-          if [[ "${replyUrls}" =~ "${authCallbackUrl}" && -n "${replyUrls}" ]]; then
-            echo "Callback URLs contain $authCallbackUrl"
-          elif [ -z $replyUrls ]; then
+          if [[ -z "${replyUrls}" ]]; then
             echo "No callback URLs Found. ISSUE!!"
+          elif jq -e --arg authCallbackUrl "$authCallbackUrl" --arg logoutUrl "$logoutUrl" 'index($authCallbackUrl) and index($logoutUrl)' <<< "$replyUrls" > /dev/null; then
+            echo "Callback URLs contain $authCallbackUrl and $logoutUrl"
           else
-            readarray -t my_array < <(echo "$replyUrls" | jq -c '.[]')
-            for item in "${my_array[@]}"; do
-              replyUrlString+="$item,"
-            done
-
-            replyUrlString+="\"$authCallbackUrl\", \"$logoutUrl\""
-            echo "Setting callback URLs: $replyUrlString"
+            replyUrls=$(jq --arg authCallbackUrl "$authCallbackUrl" --arg logoutUrl "$logoutUrl" -c 'reduce [$authCallbackUrl, $logoutUrl][] as $url (.; if index($url) then . else . + [$url] end)' <<< "$replyUrls")
+            echo "Setting callback URLs: $replyUrls"
 
             objectId=$(az ad app list --all --filter "displayname eq '${targetAppName}'" --query "[0].id" -o tsv --only-show-errors)
             objectId=${objectId//[$'\t\r\n']/}
             echo "Object ID: $objectId"
             restUrl="https://graph.microsoft.com/v1.0/applications/${objectId//[$'\t\r\n']/}"
             echo "Calling: $restUrl"
-            az rest --method PATCH --header "Content-Type=application/json" --uri $restUrl --body "{\"web\":{\"redirectUris\":[$replyUrlString]}}"
+            az rest --method PATCH --header "Content-Type=application/json" --uri $restUrl --body "{\"web\":{\"redirectUris\":$replyUrls}}"
           fi
         env:
           PR_NUMBER: ${{ github.event.number }}
+          AZURE_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
+          AZURE_CLIENT_SECRET: ${{ secrets.SP_SECRET_KEY }}
+          AZURE_TENANT_ID: ${{ secrets.SP_TENANT_ID }}
   set-external-ad-b2c-callback-urls:
     runs-on: ubuntu-latest
     steps:
@@ -58,31 +60,34 @@ jobs:
           targetAppName="darts"
           appId="363c11cb-48b9-44bf-9d06-9a3973f6f413"
 
-          az login --service-principal --username ${{ secrets.SP_CLIENT_ID_B2C}} -p=${{ secrets.SP_SECRET_KEY_B2C}} --tenant ${{ secrets.SP_TENANT_ID_B2C}} --allow-no-subscriptions
-          
+          if [[ -z "${AZURE_CLIENT_ID}" || -z "${AZURE_CLIENT_SECRET}" || -z "${AZURE_TENANT_ID}" ]]; then
+            echo "::error::Missing Azure service principal secrets for external AD B2C callback URL setup"
+            exit 1
+          fi
+
+          az login --service-principal --username "${AZURE_CLIENT_ID}" --password="${AZURE_CLIENT_SECRET}" --tenant "${AZURE_TENANT_ID}" --allow-no-subscriptions
+
           replyUrls=$(az ad app show --id "$appId" --query "web.redirectUris" -o json --only-show-errors)
           echo "Found Reply URLs"
           echo $replyUrls
 
-          if [[ "${replyUrls}" =~ "${authCallbackUrl}" && -n "${replyUrls}" ]]; then
-            echo "Callback URLs contain $authCallbackUrl"
-          elif [ -z $replyUrls ]; then
+          if [[ -z "${replyUrls}" ]]; then
             echo "No callback URLs Found. ISSUE!!"
+          elif jq -e --arg authCallbackUrl "$authCallbackUrl" --arg logoutUrl "$logoutUrl" 'index($authCallbackUrl) and index($logoutUrl)' <<< "$replyUrls" > /dev/null; then
+            echo "Callback URLs contain $authCallbackUrl and $logoutUrl"
           else
-            readarray -t my_array < <(echo "$replyUrls" | jq -c '.[]')
-            for item in "${my_array[@]}"; do
-              replyUrlString+="$item,"
-            done
-
-            replyUrlString+="\"$authCallbackUrl\", \"$logoutUrl\""
-            echo "Setting callback URLs: $replyUrlString"
+            replyUrls=$(jq --arg authCallbackUrl "$authCallbackUrl" --arg logoutUrl "$logoutUrl" -c 'reduce [$authCallbackUrl, $logoutUrl][] as $url (.; if index($url) then . else . + [$url] end)' <<< "$replyUrls")
+            echo "Setting callback URLs: $replyUrls"
 
             objectId=$(az ad app list --all --filter "displayname eq '${targetAppName}'" --query "[0].id" -o tsv --only-show-errors)
             objectId=${objectId//[$'\t\r\n']/}
             echo "Object ID: $objectId"
             restUrl="https://graph.microsoft.com/v1.0/applications/${objectId//[$'\t\r\n']/}"
             echo "Calling: $restUrl"
-            az rest --method PATCH --header "Content-Type=application/json" --uri $restUrl --body "{\"web\":{\"redirectUris\":[$replyUrlString]}}" #--debug
+            az rest --method PATCH --header "Content-Type=application/json" --uri $restUrl --body "{\"web\":{\"redirectUris\":$replyUrls}}" #--debug
           fi
         env:
           PR_NUMBER: ${{ github.event.number }}
+          AZURE_CLIENT_ID: ${{ secrets.SP_CLIENT_ID_B2C }}
+          AZURE_CLIENT_SECRET: ${{ secrets.SP_SECRET_KEY_B2C }}
+          AZURE_TENANT_ID: ${{ secrets.SP_TENANT_ID_B2C }}
